#!/usr/bin/env bash
# Reformat all project sources in place:
#   - firmware C/H under main/ via clang-format (see .clang-format, Google base)
#   - the web UI (TS/CSS/HTML/JSON) under web/ via prettier
#
# Run with no arguments to format everything. Requires clang-format on PATH and
# the web devDependencies installed (cd web && npm install).
set -euo pipefail

PROJECT_DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$PROJECT_DIR"

# --- firmware C sources -----------------------------------------------------
# Skip the generated data tables (font / favicon / logo / OUI byte arrays,
# regenerated by tools/gen-*.py); the vendored Waveshare demo is outside main/
# and never touched.
echo "clang-format: main/"
find main \( -name '*.c' -o -name '*.h' \) \
  ! -name 'font8x8_basic.h' \
  ! -name 'font8x13.h' \
  ! -name 'font6x10.h' \
  ! -name 'favicon32.h' \
  ! -name 'oled_logo.h' \
  ! -name 'header_logo.h' \
  ! -name 'oui_table.h' \
  -print0 | xargs -0 clang-format -i

# --- web UI -----------------------------------------------------------------
# prettier runs from web/ (its config + ignore live there); the generated
# main/web/index.html is out of scope.
echo "prettier: web/"
( cd web && npm run --silent format )

echo "Done."
