#!/usr/bin/env python3
"""Generate the LCD header logo (raindrop + wordmark) in two formats.

Usage: tools/gen-header.py

Composes the Rainlog raindrop (downscaled from the 512px app icon with Lanczos
antialiasing) and a "rainlog.org / bridge" wordmark (Arial Rounded MT Bold) into one RGBA
pixmap, flattened over black so the antialiased edges blend correctly with the
LCD's black background (display_blit_rgba does a hard alpha threshold, not real
blending, so the edge color must already be matted over black).

Writes two outputs from the same pixmap:
  - main/ui/header_logo.h  the C array the firmware embeds (committed, same
                           pattern as font8x13.h / oui_table.h: the ESP-IDF
                           Docker image has neither Pillow nor the assets).
  - tools/header_logo.png  a preview of exactly what the panel shows.

Re-run this when the artwork or wordmark changes.
"""

import os

from PIL import Image, ImageDraw, ImageFont

HERE = os.path.dirname(os.path.abspath(__file__))
ICON = os.path.join(HERE, "icon-512.png")
# Arial Rounded MT Bold: bubbly rounded face matching the official rainlog.org
# wordmark. Set lowercase + brand blue below for the same reason.
#
# PREREQUISITE: this font is not redistributable, so it is not in the repo and
# must be installed locally to re-run this script. You only need it to
# regenerate the header; main/ui/header_logo.h is committed, so a normal build
# never runs this. Point FONT at any rounded bold face to substitute.
FONT = "/usr/local/share/fonts/windows/ARLRDBD.TTF"
OUT_H = os.path.join(HERE, "..", "main", "ui", "header_logo.h")
OUT_PNG = os.path.join(HERE, "header_logo.png")

W, H = 172, 54  # fits the 172px-wide panel; leaves room for the version line
SS = 4          # supersample, then downscale for antialiasing
DROP_PX = 42    # raindrop size in final pixels
DROP_X = 4      # raindrop left edge in final pixels
TEXT_X = 53     # wordmark left edge in final pixels
FONT_PX = 21    # wordmark cap size in final pixels ("rainlog.org" fits at 21)
LINE_PITCH = 20  # baseline-to-baseline of the two wordmark lines, final pixels
TEXT_DY = -5    # nudge the wordmark block up from vertical center, final pixels
WORDMARK = "rainlog.org", "bridge"  # lowercase, like the official logo
TEXT_RGB = (0x62, 0xb2, 0xc2)       # brand blue


def compose():
    """Build the header pixmap as a straight-alpha RGBA image (W x H).

    RGB is matted over black (so edge color is the over-black blend the panel
    needs); alpha is the artwork coverage (so the surround stays transparent
    and the blit's <40 threshold skips near-empty pixels)."""
    cw, ch = W * SS, H * SS
    art = Image.new("RGBA", (cw, ch), (0, 0, 0, 0))

    drop = Image.open(ICON).convert("RGBA").resize((DROP_PX * SS, DROP_PX * SS), Image.LANCZOS)
    art.alpha_composite(drop, (DROP_X * SS, (ch - DROP_PX * SS) // 2))

    # Two lines on a fixed pitch (not the font's full asc+desc, which carries a
    # lot of leading), vertically centered as a block.
    d = ImageDraw.Draw(art)
    f = ImageFont.truetype(FONT, FONT_PX * SS)
    pitch = LINE_PITCH * SS
    asc = f.getmetrics()[0]
    y0 = (ch - (pitch + asc)) // 2 + TEXT_DY * SS
    d.text((TEXT_X * SS, y0), WORDMARK[0], font=f, fill=TEXT_RGB + (255,))
    d.text((TEXT_X * SS, y0 + pitch), WORDMARK[1], font=f, fill=TEXT_RGB + (255,))

    black = Image.new("RGBA", (cw, ch), (0, 0, 0, 255))
    flat = Image.alpha_composite(black, art)
    out = Image.new("RGBA", (cw, ch))
    out.putdata([(r, g, b, a) for (r, g, b, _), (_, _, _, a) in zip(flat.getdata(), art.getdata())])
    return out.resize((W, H), Image.LANCZOS)


def write_h(img):
    rows = [
        "// Generated by tools/gen-header.py - DO NOT EDIT BY HAND.",
        "// LCD header pixmap: Rainlog raindrop (from the 512px app icon) +",
        "// \"rainlog.org / bridge\" wordmark (Arial Rounded MT Bold), antialiased and matted over",
        "// black. Stored as logical RGBA, encoded via display_rgb() at draw time.",
        "#pragma once",
        "#include <stdint.h>",
        f"#define HEADER_LOGO_W {W}",
        f"#define HEADER_LOGO_H {H}",
        f"static const uint8_t header_logo_rgba[{W} * {H} * 4] = {{",
    ]
    line = "  "
    for i, (r, g, b, a) in enumerate(img.getdata()):
        line += f"{r},{g},{b},{a},"
        if (i + 1) % 8 == 0:
            rows.append(line.rstrip())
            line = "  "
    if line.strip():
        rows.append(line.rstrip())
    rows += ["};", ""]
    with open(OUT_H, "w", encoding="utf-8") as fh:
        fh.write("\n".join(rows))


def write_png(img):
    # Flatten over black (opaque) so the preview shows exactly what the panel
    # renders on its black background.
    Image.alpha_composite(Image.new("RGBA", (W, H), (0, 0, 0, 255)), img).convert("RGB").save(OUT_PNG)


def main():
    img = compose()
    write_h(img)
    write_png(img)
    print(f"gen-header: wrote {W}x{H} -> {os.path.relpath(OUT_H, HERE + '/..')}"
          f" and {os.path.relpath(OUT_PNG, HERE + '/..')}")


if __name__ == "__main__":
    main()
