#!/usr/bin/env python3
"""Generate the 6x10 and 8x13 X11 bitmap font headers.

Usage: tools/gen-font.py

Downloads the BDFs (public domain, from the X.org misc-misc font repo) to
tools/*.bdf when not cached, then emits the ASCII range of both the regular
and the bold face as C tables in the same bit order the renderer already
uses (one byte per row, LSB = leftmost column; see display_text).

The generated header is COMMITTED, same pattern as main/web/index.html and
main/net/oui_table.h: the firmware build runs in the pinned ESP-IDF Docker
image, which must never need network access.
"""

import os
import sys
import urllib.request

BASE_URL = "https://gitlab.freedesktop.org/xorg/font/misc-misc/-/raw/master"
HERE = os.path.dirname(os.path.abspath(__file__))
# (width, height, source BDFs). The 6x10 face has no upstream bold variant;
# its bold table is emboldened horizontally within the same cell.
FONTS = [(6, 10, ["6x10.bdf"]), (8, 13, ["8x13.bdf", "8x13B.bdf"])]


def parse_bdf(path, height):
    """ASCII encodings 0-127 -> list of height row bytes (MSB = left)."""
    glyphs = {}
    encoding = None
    rows = None
    with open(path, encoding="ascii", errors="replace") as f:
        for line in f:
            line = line.strip()
            if line.startswith("ENCODING "):
                encoding = int(line.split()[1])
            elif line == "BITMAP":
                rows = []
            elif line == "ENDCHAR":
                if encoding is not None and 0 <= encoding < 128 and rows:
                    glyphs[encoding] = rows[:height]
                encoding = None
                rows = None
            elif rows is not None:
                rows.append(int(line[:2], 16))
    return glyphs


def reverse_bits(b):
    return int(f"{b:08b}"[::-1], 2)


def fetch(bdf_name):
    path = os.path.join(HERE, bdf_name)  # gitignored cache
    if not os.path.exists(path):
        url = f"{BASE_URL}/{bdf_name}"
        print(f"gen-font: downloading {url}", file=sys.stderr)
        req = urllib.request.Request(url, headers={"User-Agent": "rainlog-bridge-gen-font"})
        with urllib.request.urlopen(req) as resp, open(path, "wb") as out:
            out.write(resp.read())
    return path


def emit_table(lines, table_name, glyphs, width, height, embolden=False):
    lines.append(f"static const uint8_t {table_name}[128][{height}] = {{")
    for code in range(128):
        rows = glyphs.get(code, []) if 32 <= code < 127 else []
        rows = (rows + [0] * height)[:height]
        bits = [reverse_bits(b) for b in rows]
        if embolden:
            bits = [(b | (b << 1)) & ((1 << width) - 1) for b in bits]
        body = ", ".join(f"0x{b:02X}" for b in bits)
        # Hex label for backslash: a trailing "// \" is a line continuation.
        printable_label = 32 < code < 127 and code != 0x5C
        label = chr(code) if printable_label else f"0x{code:02X}"
        lines.append(f"    {{{body}}},  // {label}")
    lines.append("};")


def generate(width, height, sources):
    name = f"font{width}x{height}"
    out = os.path.join(HERE, "..", "main", "ui", name + ".h")
    lines = [
        "// Generated by tools/gen-font.py - DO NOT EDIT BY HAND.",
        f"// X11 misc-fixed {width}x{height}, public domain. ASCII subset.",
        "// One byte per row, LSB = leftmost column.",
        "#pragma once", "", "#include <stdint.h>", "",
    ]
    glyphs = []
    for source in sources:
        face = parse_bdf(fetch(source), height)
        printable = [c for c in range(32, 127) if c in face]
        if len(printable) != 95:
            sys.exit(f"gen-font: {source}: expected 95 printable glyphs, got {len(printable)}")
        if any(len(face[c]) != height for c in printable):
            sys.exit(f"gen-font: {source}: unexpected glyph height")
        glyphs.append(face)
    emit_table(lines, name, glyphs[0], width, height)
    lines.append("")
    if len(glyphs) == 1:
        lines.append("// Synthetic bold: one-pixel horizontal expansion within the cell.")
    emit_table(lines, name + "_bold", glyphs[-1], width, height,
               embolden=len(glyphs) == 1)
    lines.append("")
    with open(out, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print(f"gen-font: wrote regular and bold faces to {os.path.relpath(out, HERE + '/..')}")


def main():
    for width, height, sources in FONTS:
        generate(width, height, sources)


if __name__ == "__main__":
    main()
