#!/usr/bin/env python3
"""Generate main/net/oui_table.h: a curated OUI -> vendor-name table.

Usage: tools/gen-oui.py [path/to/oui.csv]

Reads the IEEE MA-L registry CSV (downloaded to tools/oui.csv when no path is
given and no cache exists), keeps the assignments whose organization name
matches the curated vendor list below, and emits a sorted C table that the
firmware binary-searches (ap_clients_vendor in ap_clients.c).

The generated header is COMMITTED, same pattern as main/web/index.html: the
firmware build runs in the pinned ESP-IDF Docker image, which must never need
network access or extra Python deps. Re-run this script and commit the result
when the vendor list changes.
"""

import csv
import os
import re
import sys
import urllib.request
from collections import Counter

URL = "https://standards-oui.ieee.org/oui/oui.csv"
HERE = os.path.dirname(os.path.abspath(__file__))
CACHE = os.path.join(HERE, "oui.csv")  # gitignored (~3MB)
OUT = os.path.join(HERE, "..", "main", "net", "oui_table.h")

# Flash sanity cap: the table costs ~10 bytes/entry; trim the vendor list
# rather than raising this without thought.
MAX_ENTRIES = 6000

# (case-insensitive regex on the IEEE organization name, display label).
# First match wins. Weather-station makers first (the reason this bridge
# exists), then the WiFi modules commonly embedded in console/IoT gear, then
# the phones/laptops/home devices likely to join the bridge AP.
VENDORS = [
    (r"fine offset", "Fine Offset/Ecowitt"),
    (r"ecowitt", "Fine Offset/Ecowitt"),
    (r"ambient weather", "Ambient Weather"),
    (r"davis instruments", "Davis Instruments"),
    (r"la crosse", "La Crosse"),
    (r"chaney instrument", "AcuRite"),
    (r"espressif", "Espressif"),
    (r"texas instruments", "Texas Instruments"),
    (r"\brealtek\b", "Realtek"),
    (r"murata", "Murata"),
    (r"azurewave", "AzureWave"),
    (r"ampak", "AmpAK"),
    (r"raspberry pi", "Raspberry Pi"),
    (r"^apple", "Apple"),
    (r"samsung", "Samsung"),
    (r"^google", "Google"),
    (r"^amazon", "Amazon"),
    (r"^microsoft", "Microsoft"),
    (r"intel corporate", "Intel"),
    (r"^xiaomi", "Xiaomi"),
    # Huawei deliberately omitted: ~2000 OUI blocks for a vendor whose devices
    # (like all modern phones) randomize MACs and show "Private MAC" anyway.
    (r"oneplus", "OnePlus"),
    (r"motorola mobility", "Motorola"),
    (r"lg electronics", "LG"),
    (r"^sony", "Sony"),
    (r"asustek", "ASUS"),
    (r"tp-?link", "TP-Link"),
    (r"hon hai", "Foxconn"),
    (r"^liteon|^lite-on", "Liteon"),
]


def load_rows(path):
    with open(path, newline="", encoding="utf-8", errors="replace") as f:
        reader = csv.reader(f)
        header = next(reader)
        # Expected: Registry, Assignment, Organization Name, Organization Address
        if len(header) < 3 or header[1].strip().lower() != "assignment":
            sys.exit(f"gen-oui: unexpected CSV header: {header}")
        return [(row[1].strip(), row[2].strip()) for row in reader if len(row) >= 3]


def main():
    if len(sys.argv) > 1:
        path = sys.argv[1]
    else:
        path = CACHE
        if not os.path.exists(path):
            print(f"gen-oui: downloading {URL}", file=sys.stderr)
            req = urllib.request.Request(URL, headers={"User-Agent": "rainlog-bridge-gen-oui"})
            with urllib.request.urlopen(req) as resp, open(path, "wb") as out:
                out.write(resp.read())

    rows = load_rows(path)
    patterns = [(re.compile(pat, re.IGNORECASE), label) for pat, label in VENDORS]

    entries = {}  # assignment hex -> label
    for assignment, org in rows:
        if len(assignment) != 6:
            continue  # malformed row
        for pat, label in patterns:
            if pat.search(org):
                entries[assignment] = label
                break

    if len(entries) > MAX_ENTRIES:
        sys.exit(
            f"gen-oui: {len(entries)} entries exceeds the {MAX_ENTRIES} flash "
            "sanity cap; trim VENDORS (or consciously raise MAX_ENTRIES)."
        )

    counts = Counter(entries.values())
    ordered = sorted(entries.items(), key=lambda kv: int(kv[0], 16))

    lines = [
        "// Generated by tools/gen-oui.py - DO NOT EDIT BY HAND.",
        "// Curated subset of the IEEE MA-L (OUI) registry: weather-station makers,",
        "// embedded WiFi modules, and common phone/laptop vendors. Regenerate with",
        "// tools/gen-oui.py (downloads the registry) and commit the result.",
        f"// {len(ordered)} entries from {len(rows)} registry rows.",
        "#pragma once",
        "",
        "#include <stdint.h>",
        "",
        "typedef struct {",
        "  uint8_t prefix[3];  // first three MAC octets (the OUI)",
        "  const char *name;   // short display label",
        "} oui_entry_t;",
        "",
        "// Sorted ascending by prefix for binary search (ap_clients_vendor).",
        "static const oui_entry_t OUI_TABLE[] = {",
    ]
    for assignment, label in ordered:
        b = bytes.fromhex(assignment)
        lines.append(f'    {{{{0x{b[0]:02X}, 0x{b[1]:02X}, 0x{b[2]:02X}}}, "{label}"}},')
    lines += ["};", ""]

    with open(OUT, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    print(f"gen-oui: wrote {len(ordered)} entries to {os.path.relpath(OUT, HERE + '/..')}")
    for label, n in counts.most_common():
        print(f"  {n:5d}  {label}")


if __name__ == "__main__":
    main()
