#!/usr/bin/env python3
"""Generate main/ui/font8x13.h from the X11 misc-fixed 8x13 + 8x13B BDFs.

Usage: tools/gen-font.py

Downloads the BDFs (public domain, from the X.org misc-misc font repo) to
tools/*.bdf when not cached, then emits the ASCII range of both the regular
and the bold face as C tables in the same bit order the renderer already
uses (one byte per row, LSB = leftmost column; see display_text).

The generated header is COMMITTED, same pattern as main/web/index.html and
main/net/oui_table.h: the firmware build runs in the pinned ESP-IDF Docker
image, which must never need network access.
"""

import os
import sys
import urllib.request

BASE_URL = "https://gitlab.freedesktop.org/xorg/font/misc-misc/-/raw/master"
HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "..", "main", "ui", "font8x13.h")

# (BDF file in the misc-misc repo, C table name).
FACES = [
    ("8x13.bdf", "font8x13"),
    ("8x13B.bdf", "font8x13_bold"),
]

GLYPH_W = 8
GLYPH_H = 13


def parse_bdf(path):
    """ASCII encodings 0-127 -> list of GLYPH_H row bytes (MSB = left)."""
    glyphs = {}
    encoding = None
    rows = None
    with open(path, encoding="ascii", errors="replace") as f:
        for line in f:
            line = line.strip()
            if line.startswith("ENCODING "):
                encoding = int(line.split()[1])
            elif line == "BITMAP":
                rows = []
            elif line == "ENDCHAR":
                if encoding is not None and 0 <= encoding < 128 and rows:
                    glyphs[encoding] = rows[:GLYPH_H]
                encoding = None
                rows = None
            elif rows is not None:
                rows.append(int(line[:2], 16))
    return glyphs


def reverse_bits(b):
    return int(f"{b:08b}"[::-1], 2)


def fetch(bdf_name):
    path = os.path.join(HERE, bdf_name)  # gitignored cache
    if not os.path.exists(path):
        url = f"{BASE_URL}/{bdf_name}"
        print(f"gen-font: downloading {url}", file=sys.stderr)
        req = urllib.request.Request(url, headers={"User-Agent": "rainlog-bridge-gen-font"})
        with urllib.request.urlopen(req) as resp, open(path, "wb") as out:
            out.write(resp.read())
    return path


def emit_table(lines, table_name, glyphs):
    lines.append(f"static const uint8_t {table_name}[128][{GLYPH_H}] = {{")
    for code in range(128):
        rows = glyphs.get(code, []) if 32 <= code < 127 else []
        rows = (rows + [0] * GLYPH_H)[:GLYPH_H]
        body = ", ".join(f"0x{reverse_bits(b):02X}" for b in rows)
        # Hex label for backslash: a trailing "// \" is a line continuation.
        printable_label = 32 < code < 127 and code != 0x5C
        label = chr(code) if printable_label else f"0x{code:02X}"
        lines.append(f"    {{{body}}},  // {label}")
    lines.append("};")


def main():
    lines = [
        "// Generated by tools/gen-font.py - DO NOT EDIT BY HAND.",
        "// X11 misc-fixed 8x13 + 8x13B (public domain: \"Public domain font.",
        "// Share and enjoy.\"), ASCII subset. One byte per row, LSB = leftmost",
        "// column, matching the display_text renderer.",
        "#pragma once",
        "",
        "#include <stdint.h>",
        "",
        f"// {GLYPH_W}x{GLYPH_H} glyphs for char codes 0..127 (unprintable = blank).",
    ]
    for bdf_name, table_name in FACES:
        glyphs = parse_bdf(fetch(bdf_name))
        printable = [c for c in range(32, 127) if c in glyphs]
        if len(printable) != 95:
            sys.exit(f"gen-font: {bdf_name}: expected 95 printable glyphs, got {len(printable)}")
        emit_table(lines, table_name, glyphs)
        lines.append("")

    with open(OUT, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print(f"gen-font: wrote {len(FACES)} faces to {os.path.relpath(OUT, HERE + '/..')}")


if __name__ == "__main__":
    main()
